var sevenChecks = [
    'Violet Translator',
    'Amber Translator',
    'Emerald Translator',
    'Cobalt Translator',
    'Sky Temple Key 1',
    'Sky Temple Key 2',
    'Sky Temple Key 3',
    'Sky Temple Key 4',
    'Sky Temple Key 5',
    'Sky Temple Key 6',
    'Sky Temple Key 7',
    'Sky Temple Key 8',
    'Sky Temple Key 9',
    'Dark Agon Key 1',
    'Dark Agon Key 2',
    'Dark Agon Key 3',
    'Dark Torvus Key 1',
    'Dark Torvus Key 2',
    'Dark Torvus Key 3',
    'Ing Hive Key 1',
    'Ing Hive Key 2',
    'Ing Hive Key 3'
];
var fiveChecks = [
    'Progressive Suit',
    'Dark Beam',
    'Light Beam',
    'Annihilator Beam',
    'Darkburst',
    'Sunburst',
    'Sonic Boom'
];
var threeChecks = [
    'Morph Ball Bomb',
    'Boost Ball',
    'Power Bomb Expansion',
    'Power Bomb',
    'Space Jump Boots',
    'Spider Ball',
    'Seeker Launcher',
    'Super Missile',
    'Gravity Boost',
    'Grapple Beam',
    'Screw Attack',
    'Dark Visor',
    'Echo Visor'
];

var startingItemsList = [
    'Violet Translator',
    'Amber Translator',
    'Emerald Translator',
    'Cobalt Translator',
    'Sky Temple Key',
    'Dark Agon Key',
    'Dark Torvus Key',
    'Ing Hive Key',
    'Progressive Suit',
    'Spacer',
    'Dark Beam',
    'Light Beam',
    'Annihilator Beam',
    'Darkburst',
    'Sunburst',
    'Sonic Boom',
    'Dark Visor',
    'Echo Visor',
    'Morph Ball Bomb',
    'Power Bomb',
    'Boost Ball',
    'Spider Ball',
    'Seeker Launcher',
    'Super Missile',
    'Space Jump Boots',
    'Gravity Boost',
    'Grapple Beam',
    'Screw Attack'
]

var imgList = [
    'translator_violet',
    'translator_amber',
    'translator_emerald',
    'translator_cobalt',
    'key_sky',
    'key_argon',
    'key_torvus',
    'key_sanctuary',
    'darksuit',
    'lightsuit',
    'darkbeam',
    'lightbeam',
    'annihilator',
    'darkburst',
    'sunburst',
    'sonicboom',
    'darkvisor',
    'echovisor',
    'bomb',
    'powerbomb',
    'boostball',
    'spider',
    'seekermissile',
    'supermissile',
    'spacejump',
    'gravityboost',
    'grapple',
    'screwattack'
]