var sevenChecks = [
    'Violet Translator',
    'Amber Translator',
    'Emerald Translator',
    'Cobalt Translator',
    'Sky Temple Key 1',
    'Sky Temple Key 2',
    'Sky Temple Key 3',
    'Sky Temple Key 4',
    'Sky Temple Key 5',
    'Sky Temple Key 6',
    'Sky Temple Key 7',
    'Sky Temple Key 8',
    'Sky Temple Key 9',
    'Dark Agon Key 1',
    'Dark Agon Key 2',
    'Dark Agon Key 3',
    'Dark Torvus Key 1',
    'Dark Torvus Key 2',
    'Dark Torvus Key 3',
    'Ing Hive Key 1',
    'Ing Hive Key 2',
    'Ing Hive Key 3'
];
var fiveChecks = [
    'Progressive Suit',
    'Dark Beam',
    'Light Beam',
    'Annihilator Beam',
    'Darkburst',
    'Sunburst',
    'Sonic Boom'
];
var threeChecks = [
    'Morph Ball Bomb',
    'Boost Ball',
    'Power Bomb Expansion',
    'Power Bomb',
    'Space Jump Boots',
    'Spider Ball',
    'Seeker Launcher',
    'Super Missile',
    'Gravity Boost',
    'Grapple Beam',
    'Screw Attack',
    'Dark Visor',
    'Echo Visor'
];

var startingItemsList = [
    'bombs',
    'boostBall',
    'charge',
    'flamethrower',
    'grapple',
    'gravitySuit',
    'ice',
    'iceSpreader',
    'morphBall',
    'phazonSuit',
    'plasma',
    'powerBombs',
    'spaceJump',
    'spiderBall',
    'superMissile',
    'thermalVisor',
    'variaSuit',
    'wave',
    'wavebuster',
    'xray'
]

var imgList = [
    'three1',
    'three2',
    'five5',
    'five9',
    'five1',
    'suit2',
    'five3',
    'five8',
    'three3',
    'suit3',
    'five4',
    'three4',
    'three8',
    'three5',
    'five6',
    'three6',
    'suit1',
    'five2',
    'five7',
    'three7'
]

var artifactList = [
    'Artifact of Chozo',
    'Artifact of Elder',
    'Artifact of Lifegiver',
    'Artifact of Nature',
    'Artifact of Newborn',
    'Artifact of Spirit',
    'Artifact of Strength',
    'Artifact of Sun',
    'Artifact of Truth',
    'Artifact of Warrior',
    'Artifact of Wild',
    'Artifact of World',
]